# Generated by Django 5.2.17 on 2026-08-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='side',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=1),
        ),
    ]
